### ISSUE TITLE
Act2- Cuadro comparativo Ana Kimberly Hernández Pérez

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Anakimberly#1]
[cuadro comparativo-Tipos de texto.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Anakimberly/files/9622256/cuadro.comparativo-Tipos.de.texto.pdf)

**Comment by ErikCuevas03** [comment]
20, buen trabajo!

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
